<Project Sdk="Microsoft.NET.Sdk.">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
	  
	  
	  <!-- ВЕРСИЯ ПРИЛОЖЕНИЯ -->
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <FileVersion>1.0.0.0</FileVersion>
	  <Version>1.0.0</Version>

    <!-- Автоматическая генерация partial-классов -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- !!! Оставляем включённым: WPF сам управляет XAML -->
    <EnableDefaultItems>true</EnableDefaultItems>
    <ApplicationIcon>Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <!-- Ресурсы, которые нужно копировать -->
  <ItemGroup>
    <Content Include="remote\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <Content Include="Data\about_developer.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <Content Include="Logo.ico" />

    <!-- Медиа -->
    <Content Include="Data\media\**\*" />
  </ItemGroup>

  <!-- NuGet пакеты -->
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenXmlPowerTools" Version="4.5.3.2" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
    <PackageReference Include="RBush" Version="4.0.0" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.1" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.14" />
    <PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
